name: update-db
run-name: ${{ github.actor }} is updating the database
on: [push]
jobs:
    process-csv:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v1
          - name: run java script
            uses: jbangdev/jbang-action@v0.115.0
            with:
              script: .github/workflows/TSP.jar
          - name: commit files
            run: |
                 git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                 git config --local user.name "github-actions[bot]"
                 git add resourceData.db
                 git commit -m "Saving updated database"
          - name: push changes
            uses: ad-m/github-push-action@master
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
          
        
